---
- name: Upgrade all packages
  dnf:
    name: "*"
    state: latest

- name: Install {{ install_packages }} packages
  dnf:
    name: "{{ install_packages }}"
    state: latest

- name: Autoremove packages
  dnf:
    state: absent
    autoremove: true