---
- name: Install rpm fusion repository
  dnf:
    name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: latest

- name: Import microsoft keys
  rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Copy vscode repository file
  copy:
    src: code/vscode.repo
    dest: /etc/yum.repos.d/vscode.repo